/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-05-30 at 07:48:21 UTC 
 * Modify at your own risk.
 */

package com.flicq.tennis.appengine.model;
public final class Shot extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("ID")
  private java.lang.String iD;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("Items")
  private java.util.List<java.lang.Float> items;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("Time")
  private com.google.api.client.util.DateTime time;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String key;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getID() {
    return iD;
  }

  /**
   * @param iD iD or {@code null} for none
   */
  public Shot setID(java.lang.String iD) {
    this.iD = iD;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Float> getItems() {
    return items;
  }

  /**
   * @param items items or {@code null} for none
   */
  public Shot setItems(java.util.List<java.lang.Float> items) {
    this.items = items;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getTime() {
    return time;
  }

  /**
   * @param time time or {@code null} for none
   */
  public Shot setTime(com.google.api.client.util.DateTime time) {
    this.time = time;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public Shot setKey(java.lang.String key) {
    this.key = key;
    return this;
  }

  @Override
  public Shot set(String fieldName, Object value) {
    return (Shot) super.set(fieldName, value);
  }

  @Override
  public Shot clone() {
    return (Shot) super.clone();
  }

}
