/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-10 at 19:03:01 UTC 
 * Modify at your own risk.
 */

package com.flicq.tennis.appengine.model;

/**
 * Model definition for Shot.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the flicq. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Shot extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String aX;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String aY;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String aZ;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String counter;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String q0;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String q1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String q2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String q3;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAX() {
    return aX;
  }

  /**
   * @param aX aX or {@code null} for none
   */
  public Shot setAX(java.lang.String aX) {
    this.aX = aX;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAY() {
    return aY;
  }

  /**
   * @param aY aY or {@code null} for none
   */
  public Shot setAY(java.lang.String aY) {
    this.aY = aY;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAZ() {
    return aZ;
  }

  /**
   * @param aZ aZ or {@code null} for none
   */
  public Shot setAZ(java.lang.String aZ) {
    this.aZ = aZ;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCounter() {
    return counter;
  }

  /**
   * @param counter counter or {@code null} for none
   */
  public Shot setCounter(java.lang.String counter) {
    this.counter = counter;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Shot setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQ0() {
    return q0;
  }

  /**
   * @param q0 q0 or {@code null} for none
   */
  public Shot setQ0(java.lang.String q0) {
    this.q0 = q0;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQ1() {
    return q1;
  }

  /**
   * @param q1 q1 or {@code null} for none
   */
  public Shot setQ1(java.lang.String q1) {
    this.q1 = q1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQ2() {
    return q2;
  }

  /**
   * @param q2 q2 or {@code null} for none
   */
  public Shot setQ2(java.lang.String q2) {
    this.q2 = q2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQ3() {
    return q3;
  }

  /**
   * @param q3 q3 or {@code null} for none
   */
  public Shot setQ3(java.lang.String q3) {
    this.q3 = q3;
    return this;
  }

  @Override
  public Shot set(String fieldName, Object value) {
    return (Shot) super.set(fieldName, value);
  }

  @Override
  public Shot clone() {
    return (Shot) super.clone();
  }

}
