/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-23 at 19:42:44 UTC 
 * Modify at your own risk.
 */

package com.flicq.tennis.appengine.model;

public final class Subscribers extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Subscriber> items;

  static {
    // hack to force ProGuard to consider Subscriber used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Subscriber.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Subscriber> getItems() {
    return items;
  }

  /**
   * @param items items or {@code null} for none
   */
  public Subscribers setItems(java.util.List<Subscriber> items) {
    this.items = items;
    return this;
  }

  @Override
  public Subscribers set(String fieldName, Object value) {
    return (Subscribers) super.set(fieldName, value);
  }

  @Override
  public Subscribers clone() {
    return (Subscribers) super.clone();
  }

}
